-- 2022년 1월의 도서 판매 데이터
WITH SALES_DATA AS (
    SELECT *
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01-%'
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * SD.SALES) AS TOTAL_SALES 
FROM BOOK AS B
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
JOIN SALES_DATA AS SD ON B.BOOK_ID = SD.BOOK_ID
WHERE B.BOOK_ID IN (SELECT BOOK_ID FROM SALES_DATA)
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC;