WITH RECURSIVE GENERATION AS(
    -- 1세대 대장균 찾기
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 부모의 세대를 +1 하면서 세대를 계산
    SELECT E.ID, E.PARENT_ID, G.GENERATION +1
    FROM ECOLI_DATA E
    JOIN GENERATION G ON E.PARENT_ID = G.ID
)
SELECT ID
FROM GENERATION
WHERE GENERATION = 3
ORDER BY ID ASC;