WITH SUB_TABLE AS (SELECT IT1.ITEM_ID
FROM ITEM_TREE AS IT1
LEFT JOIN ITEM_TREE AS IT2 ON IT1.ITEM_ID = IT2.PARENT_ITEM_ID
WHERE IT2.ITEM_ID IS NULL)

SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO AS II
JOIN SUB_TABLE AS S ON II.ITEM_ID = S.ITEM_ID
ORDER BY ITEM_ID DESC;