-- 코드를 입력하세요
SELECT DATE_FORMAT(SALE_DATA.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, SALE_DATA.PRODUCT_ID, SALE_DATA.USER_ID, SALE_DATA.SALES_AMOUNT
FROM ( 
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT	
    FROM ONLINE_SALE
    WHERE YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 3
    
    UNION ALL
    
    SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT	
    FROM OFFLINE_SALE
   WHERE YEAR(SALES_DATE) = 2022
    AND MONTH(SALES_DATE) = 3
    
) AS SALE_DATA
ORDER BY SALES_DATE ASC, SALE_DATA.PRODUCT_ID ASC, SALE_DATA.USER_ID ASC;