-- 11월에 대여중인 CAR
WITH SUB AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
        AND END_DATE >= '2022-11-01'
)


SELECT C.CAR_ID, C.CAR_TYPE, 
    FLOOR(C.DAILY_FEE * 30 * (1 - (IFNULL(D.DISCOUNT_RATE, 0) / 100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON C.CAR_TYPE = D.CAR_TYPE 
    AND D.DURATION_TYPE = '30일 이상'
WHERE 
    C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM SUB) -- 11월 대여 가능한 것들에서
    AND FLOOR(C.DAILY_FEE * 30 * (1 - (IFNULL(D.DISCOUNT_RATE, 0) / 100))) >= 500000 -- 50만원 이상
    AND FLOOR(C.DAILY_FEE * 30 * (1 - (IFNULL(D.DISCOUNT_RATE, 0) / 100))) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;