SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    FLOOR(C.DAILY_FEE * 30 * (1 - (IFNULL(D.DISCOUNT_RATE, 0) / 100))) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR C
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON C.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30'
      AND END_DATE >= '2022-11-01'
)

    AND (C.DAILY_FEE * 30 * (1 - (IFNULL(D.DISCOUNT_RATE, 0) / 100))) >= 500000
    AND (C.DAILY_FEE * 30 * (1 - (IFNULL(D.DISCOUNT_RATE, 0) / 100))) < 2000000
ORDER BY
    FEE DESC,
    C.CAR_TYPE ASC,
    C.CAR_ID DESC;
