WITH RANKED AS (
    SELECT ID, SIZE_OF_COLONY,
        NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS Q
    FROM ECOLI_DATA
)
SELECT ID, 
    CASE
        WHEN Q = 1 THEN 'CRITICAL'
        WHEN Q = 2 THEN 'HIGH'
        WHEN Q = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM RANKED
ORDER BY ID ASC;