SELECT U.USER_ID, U.NICKNAME, 
    CONCAT(U.CITY, ' ', U.STREET_ADDRESS1,' ', U.STREET_ADDRESS2) AS '전체주소',
    CONCAT(
        SUBSTRING(U.TLNO, 1, 3), '-', -- 앞 3자리
        SUBSTRING(U.TLNO, 4, 4), '-', -- 중간 4자리
        SUBSTRING(U.TLNO, 8, 4) -- 끝 4 자리
    ) AS 전화번호
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
GROUP BY U.USER_ID, U.NICKNAME
HAVING COUNT(*) >=3
ORDER BY USER_ID DESC;
