-- 2021년도에 가입한 회원들 
WITH SUB AS (
    SELECT DISTINCT USER_ID
    FROM USER_INFO
    WHERE JOINED LIKE '2021%'
    GROUP BY USER_ID
)

SELECT YEAR(O.SALES_DATE) AS YEAR,
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT U.USER_ID) / (SELECT COUNT(*) FROM SUB), 1) AS PUCHASED_RATIO
FROM USER_INFO AS U
JOIN ONLINE_SALE AS O ON U.USER_ID = O.USER_ID
WHERE U.JOINED LIKE '2021%'
GROUP BY YEAR(O.SALES_DATE), MONTH(O.SALES_DATE)