WITH RECURSIVE GENERATION AS(
    SELECT E.ID, E.PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA AS E
    WHERE E.PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION+1
    FROM ECOLI_DATA AS E
    JOIN GENERATION AS G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, G1.GENERATION
FROM GENERATION AS G1
LEFT JOIN GENERATION AS G2 ON G1.ID = G2.PARENT_ID
WHERE G2.PARENT_ID IS NULL
GROUP BY G1.GENERATION;