WITH RECURSIVE GENERATION_TABLE AS (
    -- 1세대
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    -- 재귀로 자식 찾기
    SELECT E.ID, E.PARENT_ID, GENERATION + 1
    FROM ECOLI_DATA AS E
    JOIN GENERATION_TABLE AS G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, P.GENERATION
FROM GENERATION_TABLE AS P
LEFT JOIN ECOLI_DATA AS C ON C.PARENT_ID = P.ID
WHERE C.ID IS NULL
GROUP BY P.GENERATION
ORDER BY GENERATION ASC;
