WITH TOTAL_FIRST_HALF AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
), 
TOTAL_JULY AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT TFH.FLAVOR
FROM TOTAL_FIRST_HALF AS TFH 
JOIN TOTAL_JULY AS TJ ON TFH.FLAVOR = TJ.FLAVOR
ORDER BY (TFH.TOTAL_ORDER + TJ.TOTAL_ORDER) DESC
LIMIT 3;