WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_tABLE WHERE HOUR < 23
)

SELECT T.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME_TABLE AS T
LEFT JOIN ANIMAL_OUTS AS A ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR ASC;