-- 0부터 23까지의 숫자 생성 (시간대 테이블 역할)
WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOURS WHERE HOUR < 23
)

SELECT
    H.HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM HOURS AS H
LEFT JOIN (
    SELECT
        HOUR(DATETIME) AS HOUR,
        ANIMAL_ID
    FROM ANIMAL_OUTS
) AS A ON H.HOUR = A.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR ASC;