-- 완료된 중고 거래
WITH DONE_TABLE AS (
    SELECT *
    FROM USED_GOODS_BOARD AS B
    JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    WHERE STATUS = 'DONE'
)
SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM DONE_TABLE
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;