WITH DONE_TABLE AS (
    SELECT *
    FROM USED_GOODS_BOARD AS B
    JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    WHERE B.STATUS = 'DONE'
)

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM DONE_TABLE
GROUP BY USER_ID, NICKNAME
HAVING SUM(PRICE) >= 700000
ORDER BY SUM(PRICE) ASC;