
WITH SUB_TABLE AS(
    SELECT U.USER_ID, U.NICKNAME, B.PRICE
    FROM USED_GOODS_BOARD AS B
    JOIN USED_GOODS_USER AS U ON B.WRITER_ID = U.USER_ID
    WHERE B.STATUS = 'DONE'
)

SELECT USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM SUB_TABLE
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES ASC;
