WITH SUB AS 
(SELECT G.EMP_NO, AVG(G.SCORE) AS SCORE_AVG
FROM HR_DEPARTMENT AS D
JOIN HR_EMPLOYEES AS E ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO)

SELECT E.EMP_NO, E.EMP_NAME,
        CASE
            WHEN S.SCORE_AVG >= 96 THEN 'S'
            WHEN S.SCORE_AVG >= 90 THEN 'A'
            WHEN S.SCORE_AVG >= 80 THEN 'B'
            ELSE 'C'
        END AS GRADE,
        CASE 
            WHEN S.SCORE_AVG >= 96 THEN E.SAL * 0.2
            WHEN S.SCORE_AVG >= 90 THEN E.SAL * 0.15
            WHEN S.SCORE_AVG >= 80 THEN E.SAL * 0.1
            ELSE 0
        END AS BONUS
        
FROM SUB AS S
JOIN HR_EMPLOYEES AS E ON S.EMP_NO = E.EMP_NO
ORDER BY EMP_NO ASC;

