-- 가장 많ㅎ이 리뷰한 회원 id
WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
TOP_REVIEWER AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    ORDER BY REVIEW_CNT DESC
    LIMIT 1
)

-- 해당 회원으로 모든 리뷰 가져오기
SELECT
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS M ON R.MEMBER_ID = M.MEMBER_ID
JOIN TOP_REVIEWER AS T ON R.MEMBER_ID = T.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;
