SELECT II2.ITEM_ID, II2.ITEM_NAME, II2.RARITY
FROM ITEM_INFO AS II 
JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
JOIN ITEM_INFO AS II2 ON IT.ITEM_ID = II2.ITEM_ID
WHERE II.RARITY = 'RARE'
ORDER BY ITEM_ID DESC;
