WITH MAX_SIZE_IN_DIFFERENTIATION_DATE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)



SELECT MD.YEAR, (MD.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
JOIN MAX_SIZE_IN_DIFFERENTIATION_DATE AS MD
    ON YEAR(E.DIFFERENTIATION_DATE) = MD.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;
