WITH RANK_FISH AS (
    SELECT F.ID, F.FISH_TYPE, F.LENGTH, N.FISH_NAME,
    ROW_NUMBER() OVER(PARTITION BY F.FISH_TYPE ORDER BY F.LENGTH DESC) AS RN
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO AS N ON F.FISH_TYPE = N.FISH_TYPE
    WHERE F.LENGTH IS NOT NULL
)

SELECT ID, FISH_NAME, LENGTH
FROM RANK_FISH
WHERE RN = 1
ORDER BY ID;