SELECT SUM(SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT AS D
JOIN HR_EMPLOYEES AS E ON D.DEPT_ID = E.DEPT_ID
JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
GROUP BY G.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SCORE DESC
LIMIT 1;