WITH RANKING AS (
    SELECT BOARD_ID,
        DENSE_RANK() OVER (ORDER BY VIEWS DESC) AS RANKING
    FROM USED_GOODS_BOARD
)

SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, 	FILE_EXT) AS FILE_PATH
FROM RANKING AS R
JOIN USED_GOODS_FILE AS F ON R.BOARD_ID = F.BOARD_ID
WHERE R.RANKING = 1
ORDER BY F.FILE_ID DESC;