WITH RANK_TABLE AS (
SELECT CATEGORY, 
    ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN,
      PRICE,
      PRODUCT_NAME
FROM FOOD_PRODUCT
)

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM RANK_TABLE
WHERE RN = 1
    AND CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC;
